# -----------------------------------------------------------------------------------------------------------------
# proof-of-concept dynamic object oriented tree generator 
# for terasology project
# written by cynthia kurtz
# -----------------------------------------------------------------------------------------------------------------

INDENT = '    '
DIRECTIONS = ["north", "east", "south", "west", "up", "down"]

SIZE_OF_SPACE_XY = 100
SIZE_OF_SPACE_Z = 300
GROUND_LEVEL = 100

PATCHY_SUN = False

PATCHY_WATER = True
NUM_WATER_PATCHES = 50
WATER_PATCH_RADIUS = 2

PATCHY_MINERALS = True
NUM_MINERAL_PATCHES = 50
MINERAL_PATCH_RADIUS = 2

DRAW_ROOTS = True
DRAW_STEMS = True
DRAW_LEAF_CLUSTERS = True
DRAW_MERISTEMS = True
DRAW_FLOWER_CLUSTERS = True
DRAW_FRUIT_CLUSTERS = True

# for all parameters that impact both stems and roots, the first in the list is stems, the second is roots

# MERISTEMS - BIOMASS, WATER, NUTRIENTS
START_MERISTEM_BIOMASS = [11, 7]
BIOMASS_TO_MAKE_ONE_PHYTOMER = [10, 6]
BIOMASS_TO_MAKE_ONE_FLOWER_CLUSTER = 10
BIOMASS_USED_BY_MERISTEM_PER_DAY = [0.1, 0.1]
MERISTEM_DIES_IF_BIOMASS_GOES_BELOW = [0.01, 0.01]

# MERISTEMS - BRANCHING
AXILLARY_MERISTEMS_PER_INTERNODE = [2, 2]
BRANCHING_PROBABILITY = [0.4, 0.6]
APICAL_DOMINANCE_EXTENDS_FOR = [6, 8]
MAX_NUM_INTERNODES_ON_TREE_EVER = [50, 50] # this is a check on all the other parameters blowing up into a giant tree

# MERISTEMS - DRAWING
COLOR_MERISTEM = ["#7CFC00", "#000000"]
COLOR_MERISTEM_DEAD = ['r', 'r']# ["#8B8B83", "#000000"]

# INTERNODES - BIOMASS, WATER, NUTRIENTS
START_INTERNODE_BIOMASS = [1, 1]
OPTIMAL_INTERNODE_BIOMASS = [6, 3]
BIOMASS_USED_BY_INTERNODE_PER_DAY = [0.1, 0.1]
INTERNODE_DIES_IF_BIOMASS_GOES_BELOW = [0.01, 0.01]
INTERNODES_SEEK_RADIUS = [1, 2]

BIOMASS_DISTRIBUTION_SPREAD_PERCENT = [70, 50]
BIOMASS_DISTRIBUTION_ORDER = [
							["root", "leaf clusters", "fruit clusters", "flower clusters", 'branches', 'axillary meristems', "apical meristems", "child"],
							["above-ground tree", 'branches', 'axillary meristems', "apical meristems", "child"],
							]


ROOT_WATER_EXTRACTION_EFFICIENCY = 0.5
ROOT_MINERAL_EXTRACTION_EFFICIENCY = 0.5
ROOT_WATER_EXTRACTION_RADIUS = 2
ROOT_MINERAL_EXTRACTION_RADIUS = 2
ROOTS_CAN_GROW_THIS_MANY_BLOCKS_ABOVE_GROUND = 0

WATER_DISTRIBUTION_SPREAD_PERCENT = [50, 70]
WATER_DISTRIBUTION_ORDER = [
							["leaf clusters", "child", 'branches'],
							["above-ground tree", 'parent'],
							]

MINERALS_DISTRIBUTION_SPREAD_PERCENT = [50, 70]
MINERALS_DISTRIBUTION_ORDER = [
							["leaf clusters", "child", 'branches'],
							["above-ground tree", 'parent'],
							]

INTERNODES_TURN_WOODY_AFTER_THIS_MANY_DAYS = [8,8]

# INTERNODES - DRAWING

INTERNODE_LENGTH_AT_CREATION = [3, 3] # no less than 3, to have room for buds and leafClusters
INTERNODE_LENGTH_AT_FULL_SIZE = [12, 6]
INTERNODE_WIDTH_AT_CREATION = [1, 1]
INTERNODE_WIDTH_AT_FULL_SIZE = [3, 3]
FIRST_INTERNODE_LENGTH_AT_CREATION = [5, 5]
FIRST_INTERNODE_LENGTH_AT_FULL_SIZE = [15, 13]

ANGLE_BETWEEN_STEM_AND_BRANCH_OFF_TRUNK = [40, 40]
ANGLE_BETWEEN_STEM_AND_BRANCH_NOT_OFF_TRUNK = [30, 30]
RANDOM_INTERNODE_SWAY = [20, 20]
COLOR_INTERNODE_WOODY = "#CC7F32" # root not needed
COLOR_INTERNODE_NONWOODY = ["#8B7500", "#CC7F32"]
COLOR_INTERNODE_DEAD = ['r', 'r']# ["#292421", "#CC7F32"]

# LEAF CLUSTERS - BIOMASS, WATER, NUTRIENTS
START_LEAF_CLUSTER_BIOMASS = 1
OPTIMAL_LEAF_CLUSTER_BIOMASS = 8
BIOMASS_USED_BY_LEAF_CLUSTER_PER_DAY = 0.5
LEAF_CLUSTER_DIES_IF_BIOMASS_GOES_BELOW = 0.01

# LEAF CLUSTERS - PHOTOSYNTHESIS
OPTIMAL_LEAF_PHOTOSYNTHATE = 40
WATER_FOR_OPTIMAL_PHOTOSYNTHESIS = 5
MINERALS_FOR_OPTIMAL_PHOTOSYNTHESIS = 5
SHADE_TOLERANCE = 10

# LEAF CLUSTERS - DRAWING
LEAF_CLUSTER_LENGTH_AT_FULL_SIZE = 4
LEAF_CLUSTER_LENGTH_AT_CREATION = 1
LEAF_CLUSTER_ANGLE_WITH_STEM = 40
LEAF_CLUSTER_SHAPE_ANGLE = 30
RANDOM_LEAF_CLUSTER_SWAY = 20
LEAF_CLUSTER_SHAPE_PATTERN = "12"
LEAF_CLUSTER_SIDES = 4
COLOR_LEAF_CLUSTER = "#488214"
COLOR_LEAF_CLUSTER_DEAD = 'r' #"#5E2605"

# FLOWERS - TIMING
REPRODUCTIVE_MODE_STARTS_ON_DAY = 20
PROBABILITY_THAT_ANY_APICAL_MERISTEM_WILL_SWITCH_TO_REPRO_MODE = 0.5
PROBABILITY_THAT_ANY_AXILLARY_MERISTEM_WILL_SWITCH_TO_REPRO_MODE = 0.5

# FLOWER CLUSTERS - BIOMASS, WATER, NUTRIENTS
START_FLOWER_CLUSTER_BIOMASS = 1
OPTIMAL_FLOWER_CLUSTER_BIOMASS = 8
BIOMASS_USED_BY_FLOWER_CLUSTER_PER_DAY = 0.5
FLOWER_CLUSTER_DIES_IF_BIOMASS_GOES_BELOW = 0.01

# FLOWER CLUSTERS - DRAWING
FLOWER_CLUSTER_LENGTH_AT_FULL_SIZE = 5
FLOWER_CLUSTER_LENGTH_AT_CREATION = 1
FLOWER_CLUSTER_ANGLE_WITH_STEM = 40
FLOWER_CLUSTER_SHAPE_ANGLE = 30
FLOWER_CLUSTER_SIDES = 3
RANDOM_FLOWER_CLUSTER_SWAY = 20
FLOWER_CLUSTER_SHAPE_PATTERN = "1234"
COLOR_FLOWER_CLUSTER = "#FFE303"
COLOR_FLOWER_CLUSTER_DEAD = 'r'# "#5E2605"

# FRUIT CLUSTERS - BIOMASS, WATER, NUTRIENTS
START_FRUIT_CLUSTER_BIOMASS = 1
OPTIMAL_FRUIT_CLUSTER_BIOMASS = 8
BIOMASS_USED_BY_FRUIT_CLUSTER_PER_DAY = 0.5
FRUIT_CLUSTER_DIES_IF_BIOMASS_GOES_BELOW = 0.01

# FRUIT CLUSTERS - DRAWING
FRUIT_CLUSTER_LENGTH_AT_FULL_SIZE = 5
FRUIT_CLUSTER_LENGTH_AT_CREATION = 1
FRUIT_CLUSTER_ANGLE_WITH_STEM = 40
FRUIT_CLUSTER_SHAPE_ANGLE = 30
FRUIT_CLUSTER_SIDES = 2
RANDOM_FRUIT_CLUSTER_SWAY = 20
FRUIT_CLUSTER_SHAPE_PATTERN = "1232"
COLOR_FRUIT_CLUSTER = "#CD0000"
COLOR_FRUIT_CLUSTER_DEAD = 'r'#"#5E2605"

