# -----------------------------------------------------------------------------------------------------------------
# proof-of-concept dynamic object oriented tree generator 
# for terasology project
# written by cynthia kurtz
# -----------------------------------------------------------------------------------------------------------------

INDENT = '    '
DIRECTIONS = ["north", "east", "south", "west", "up", "down"]

SIZE_OF_SPACE_XY = 100
SIZE_OF_SPACE_Z = 200
GROUND_LEVEL = 100

PATCHY_SUN = True

PATCHY_WATER = True
NUM_WATER_PATCHES = 50
WATER_PATCH_RADIUS = 2

PATCHY_MINERALS = True
NUM_MINERAL_PATCHES = 50
MINERAL_PATCH_RADIUS = 2

DRAW_ROOTS = True
DRAW_STEMS = True
DRAW_LEAVES = True
DRAW_MERISTEMS = True

# for all parameters that impact both stems and roots, the first in the list is stems, the second is roots

# MERISTEMS - BIOMASS, WATER, NUTRIENTS
START_MERISTEM_BIOMASS = [11, 7]
BIOMASS_TO_MAKE_ONE_PHYTOMER = [10, 6]
BIOMASS_USED_BY_MERISTEM_PER_DAY = [0.1, 0.1]
MERISTEM_DIES_IF_BIOMASS_GOES_BELOW = [0.01, 0.01]

START_MERISTEM_WATER = [6, 6]
WATER_TO_MAKE_ONE_PHYTOMER = [5, 5]
WATER_USED_BY_MERISTEM_PER_DAY = [0.1, 0.1]
MERISTEM_DIES_IF_WATER_GOES_BELOW = [0.01, 0.01]

START_MERISTEM_MINERALS = [6, 6]
MINERALS_TO_MAKE_ONE_PHYTOMER = [5, 5]
MINERALS_USED_BY_MERISTEM_PER_DAY = [0.1, 0.1]
MERISTEM_DIES_IF_MINERALS_GOES_BELOW = [0.01, 0.01]

# MERISTEMS - BRANCHING
AXILLARY_MERISTEMS_PER_INTERNODE = [2, 2]
BRANCHING_PROBABILITY = [0.4, 0.6]
APICAL_DOMINANCE_EXTENDS_FOR = [5, 6]
MAX_NUM_INTERNODES_ON_TREE_EVER = [50, 50] # this is a check on all the other parameters blowing up into a giant tree

# MERISTEMS - DRAWING
COLOR_MERISTEM = ["#7CFC00", "#000000"]
COLOR_MERISTEM_DEAD = ["#8B8B83", "#000000"]

# INTERNODES - BIOMASS, WATER, NUTRIENTS
START_INTERNODE_BIOMASS = [1, 1]
OPTIMAL_INTERNODE_BIOMASS = [6, 3]
BIOMASS_USED_BY_INTERNODE_PER_DAY = [0.1, 0.1]
INTERNODE_DIES_IF_BIOMASS_GOES_BELOW = [0.01, 0.01]
INTERNODES_SEEK_RADIUS = [2, 4]

BIOMASS_DISTRIBUTION_SPREAD_PERCENT = [70, 50]
BIOMASS_DISTRIBUTION_ORDER = [
							["root", "leaf clusters",'branches', 'axillary meristems', "apical meristems", "child"],
							["above-ground tree", 'branches', 'axillary meristems', "apical meristems", "child"],
							]

START_INTERNODE_WATER = [1, 4]
OPTIMAL_INTERNODE_WATER = [6, 2]
WATER_USED_BY_INTERNODE_PER_DAY = [0.1, 0.05]
INTERNODE_DIES_IF_WATER_GOES_BELOW = [0.01, 0.01]

ROOT_WATER_EXTRACTION_EFFICIENCY = 0.5
ROOT_MINERAL_EXTRACTION_EFFICIENCY = 0.5
ROOT_WATER_EXTRACTION_RADIUS = 2
ROOT_MINERAL_EXTRACTION_RADIUS = 2
ROOTS_CAN_GROW_THIS_MANY_BLOCKS_ABOVE_GROUND = 5

WATER_DISTRIBUTION_SPREAD_PERCENT = [50, 70]
WATER_DISTRIBUTION_ORDER = [
							["leaf clusters","child",'branches', 'axillary meristems', "apical meristems"],
							["above-ground tree", 'parent', 'axillary meristems', "apical meristems"],
							]

START_INTERNODE_MINERALS = [1, 1]
OPTIMAL_INTERNODE_MINERALS = [6, 3]
MINERALS_USED_BY_INTERNODE_PER_DAY = [0.1, 0.1]
INTERNODE_DIES_IF_MINERALS_GOES_BELOW = [0.01, 0.01]

MINERALS_DISTRIBUTION_SPREAD_PERCENT = [50, 70]
MINERALS_DISTRIBUTION_ORDER = [
							["leaf clusters","child",'branches', 'axillary meristems', "apical meristems"],
							["above-ground tree", 'parent', 'axillary meristems', "apical meristems"],
							]

# INTERNODES - PHOTOSYNTHESIS
OPTIMAL_INTERNODE_PHOTOSYNTHATE = 10 # root not needed
INTERNODES_TURN_WOODY_AFTER_THIS_MANY_DAYS = [8,8]

# INTERNODES - DRAWING

INTERNODE_LENGTH_AT_CREATION = [3, 3] # no less than 3, to have room for buds and leafClusters
INTERNODE_LENGTH_AT_FULL_SIZE = [12, 10]
INTERNODE_WIDTH_AT_CREATION = [1, 1]
INTERNODE_WIDTH_AT_FULL_SIZE = [3, 3]
FIRST_INTERNODE_LENGTH_AT_CREATION = [5, 5]
FIRST_INTERNODE_LENGTH_AT_FULL_SIZE = [15, 13]

ANGLE_BETWEEN_STEM_AND_BRANCH_OFF_TRUNK = [40, 40]
ANGLE_BETWEEN_STEM_AND_BRANCH_NOT_OFF_TRUNK = [30, 30]
RANDOM_INTERNODE_SWAY = [20, 20]
COLOR_INTERNODE_WOODY = "#CC7F32" # root not needed
COLOR_INTERNODE_NONWOODY = ["#8B7500", "red"]##CC7F32"]
COLOR_INTERNODE_DEAD = ["#292421", "#CC7F32"]

# LEAF CLUSTERS - BIOMASS, WATER, NUTRIENTS
START_LEAF_CLUSTER_BIOMASS = 1
OPTIMAL_LEAF_CLUSTER_BIOMASS = 8
BIOMASS_USED_BY_LEAF_CLUSTER_PER_DAY = 0.5
LEAF_CLUSTER_DIES_IF_BIOMASS_GOES_BELOW = 0.01

START_LEAF_CLUSTER_WATER = 1
OPTIMAL_LEAF_CLUSTER_WATER = 6
WATER_USED_BY_LEAF_CLUSTER_PER_DAY = 0.1
LEAF_CLUSTER_DIES_IF_WATER_GOES_BELOW = 0.01

START_LEAF_CLUSTER_MINERALS = 1
OPTIMAL_LEAF_CLUSTER_MINERALS = 6
MINERALS_USED_BY_LEAF_CLUSTER_PER_DAY = 0.1
LEAF_CLUSTER_DIES_IF_MINERALS_GOES_BELOW = 0.01

# LEAF CLUSTERS - PHOTOSYNTHESIS
OPTIMAL_LEAF_PHOTOSYNTHATE = 40
SHADE_TOLERANCE = 10

# LEAF CLUSTERS - DRAWING
LEAF_CLUSTER_LENGTH_AT_FULL_SIZE = 5
LEAF_CLUSTER_LENGTH_AT_CREATION = 1
LEAF_CLUSTER_ANGLE_WITH_STEM = 40
LEAF_CLUSTER_SHAPE_ANGLE = 30
RANDOM_LEAF_CLUSTER_SWAY = 20
LEAF_CLUSTER_SHAPE_PATTERN = "1122"
COLOR_LEAF_CLUSTER = "#488214"
COLOR_LEAF_CLUSTER_DEAD = "#5E2605"



